/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void leftClick(GButton source, GEvent event) { //_CODE_:leftBtn:308221:
  myPort.write('l');
  showCommands.setText("Zumo moved left");
} //_CODE_:leftBtn:308221:

public void rightClick(GButton source, GEvent event) { //_CODE_:rightBtn:604378:
  myPort.write('r');
  showCommands.setText("Zumo moved right");
} //_CODE_:rightBtn:604378:

public void forwardClick(GButton source, GEvent event) { //_CODE_:forwardBtn:348760:
  myPort.write('w');
  showCommands.setText("Zumo moved forward");
} //_CODE_:forwardBtn:348760:

public void backClick(GButton source, GEvent event) { //_CODE_:backBtn:984108:
   myPort.write('s');
   showCommands.setText("Zumo is reversing");
} //_CODE_:backBtn:984108:

public void stopClick(GButton source, GEvent event) { //_CODE_:stopBtn:713639:
  myPort.write('x');
  showCommands.setText("Stop Zumo");
} //_CODE_:stopBtn:713639:

public void autoAction(GButton source, GEvent event) { //_CODE_:autoBtn:225239:
  myPort.write('p');
  showCommands.setText("Activate corridor state");
} //_CODE_:autoBtn:225239:

public void completeAction(GButton source, GEvent event) { //_CODE_:completeBtn:927881:
  myPort.write('c');
  showCommands.setText("Manual control over");
} //_CODE_:completeBtn:927881:

public void showCommandsAction(GTextField source, GEvent event) { //_CODE_:showCommands:358095:
} //_CODE_:showCommands:358095:

public void calibrateAction(GButton source, GEvent event) { //_CODE_:calibrateBtn:772610:
 myPort.write('t');
 showCommands.setText("Calibrating zumo to the environment");
} //_CODE_:calibrateBtn:772610:

public void roomAction(GButton source, GEvent event) { //_CODE_:roomBtn:308807:
 myPort.write('z');
 showCommands.setText("Room found");
} //_CODE_:roomBtn:308807:

public void showTextAction(GTextArea source, GEvent event) { //_CODE_:showText:987080:
} //_CODE_:showText:987080:

public void showRoomAction(GTextField source, GEvent event) { //_CODE_:showRoom:967927:
} //_CODE_:showRoom:967927:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  leftBtn = new GButton(this, 210, 70, 80, 30);
  leftBtn.setText("Left");
  leftBtn.setTextBold();
  leftBtn.addEventHandler(this, "leftClick");
  rightBtn = new GButton(this, 390, 70, 80, 31);
  rightBtn.setText("Right");
  rightBtn.setTextBold();
  rightBtn.addEventHandler(this, "rightClick");
  forwardBtn = new GButton(this, 300, 30, 80, 30);
  forwardBtn.setText("Forward");
  forwardBtn.setTextBold();
  forwardBtn.addEventHandler(this, "forwardClick");
  backBtn = new GButton(this, 300, 110, 80, 30);
  backBtn.setText("Back");
  backBtn.setTextBold();
  backBtn.addEventHandler(this, "backClick");
  stopBtn = new GButton(this, 300, 70, 80, 30);
  stopBtn.setText("Stop");
  stopBtn.setTextBold();
  stopBtn.addEventHandler(this, "stopClick");
  label1 = new GLabel(this, 20, 150, 140, 20);
  label1.setText("Messages from Zumo:");
  label1.setTextBold();
  label1.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  label1.setOpaque(false);
  autoBtn = new GButton(this, 110, 50, 80, 30);
  autoBtn.setText("Auto Move");
  autoBtn.setTextBold();
  autoBtn.addEventHandler(this, "autoAction");
  completeBtn = new GButton(this, 110, 10, 80, 30);
  completeBtn.setText("Complete");
  completeBtn.setTextBold();
  completeBtn.addEventHandler(this, "completeAction");
  label2 = new GLabel(this, 20, 100, 160, 20);
  label2.setText("Commands sent to Zumo:");
  label2.setTextBold();
  label2.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  label2.setOpaque(false);
  showCommands = new GTextField(this, 20, 120, 250, 30, G4P.SCROLLBARS_NONE);
  showCommands.setOpaque(true);
  showCommands.addEventHandler(this, "showCommandsAction");
  calibrateBtn = new GButton(this, 20, 10, 80, 30);
  calibrateBtn.setText("Calibrate");
  calibrateBtn.setTextBold();
  calibrateBtn.addEventHandler(this, "calibrateAction");
  roomBtn = new GButton(this, 20, 50, 80, 30);
  roomBtn.setText("Room");
  roomBtn.setTextBold();
  roomBtn.addEventHandler(this, "roomAction");
  showText = new GTextArea(this, 20, 170, 250, 80, G4P.SCROLLBARS_VERTICAL_ONLY | G4P.SCROLLBARS_AUTOHIDE);
  showText.setOpaque(true);
  showText.addEventHandler(this, "showTextAction");
  showRoom = new GTextField(this, 20, 270, 260, 30, G4P.SCROLLBARS_NONE);
  showRoom.setOpaque(true);
  showRoom.addEventHandler(this, "showRoomAction");
  label3 = new GLabel(this, 20, 250, 90, 20);
  label3.setText("Room details:");
  label3.setTextBold();
  label3.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  label3.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton leftBtn; 
GButton rightBtn; 
GButton forwardBtn; 
GButton backBtn; 
GButton stopBtn; 
GLabel label1; 
GButton autoBtn; 
GButton completeBtn; 
GLabel label2; 
GTextField showCommands; 
GButton calibrateBtn; 
GButton roomBtn; 
GTextArea showText; 
GTextField showRoom; 
GLabel label3; 