/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:textarea1:653858:
  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:textarea1:653858:

public void sendBtnClick(GButton source, GEvent event) { //_CODE_:sendBtn:500642:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:sendBtn:500642:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:568846:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:568846:

public void leftClick(GButton source, GEvent event) { //_CODE_:leftBtn:308221:
  myPort.write('a');
} //_CODE_:leftBtn:308221:

public void rightClick(GButton source, GEvent event) { //_CODE_:rightBtn:604378:
  myPort.write('r');
} //_CODE_:rightBtn:604378:

public void forwardClick(GButton source, GEvent event) { //_CODE_:forwardBtn:348760:
  myPort.write('w');
} //_CODE_:forwardBtn:348760:

public void backClick(GButton source, GEvent event) { //_CODE_:backBtn:984108:
   myPort.write('s');
} //_CODE_:backBtn:984108:

public void stopClick(GButton source, GEvent event) { //_CODE_:stopBtn:713639:
  myPort.write('x');
} //_CODE_:stopBtn:713639:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  textarea1 = new GTextArea(this, 237, 11, 198, 199, G4P.SCROLLBARS_BOTH | G4P.SCROLLBARS_AUTOHIDE);
  textarea1.setText("Messages from Zumo");
  textarea1.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  textarea1.setOpaque(true);
  textarea1.addEventHandler(this, "textarea1_change1");
  sendBtn = new GButton(this, 20, 280, 91, 60);
  sendBtn.setTextAlign(GAlign.LEFT, GAlign.TOP);
  sendBtn.setText("Send message to Zumo");
  sendBtn.setTextBold();
  sendBtn.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  sendBtn.addEventHandler(this, "sendBtnClick");
  textfield1 = new GTextField(this, 110, 300, 160, 30, G4P.SCROLLBARS_NONE);
  textfield1.setText("Messages To Zumo");
  textfield1.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  leftBtn = new GButton(this, 20, 80, 80, 30);
  leftBtn.setText("Left");
  leftBtn.setTextBold();
  leftBtn.addEventHandler(this, "leftClick");
  rightBtn = new GButton(this, 140, 80, 80, 31);
  rightBtn.setText("Right");
  rightBtn.setTextBold();
  rightBtn.addEventHandler(this, "rightClick");
  forwardBtn = new GButton(this, 80, 40, 80, 30);
  forwardBtn.setText("Forward");
  forwardBtn.setTextBold();
  forwardBtn.addEventHandler(this, "forwardClick");
  backBtn = new GButton(this, 80, 120, 80, 30);
  backBtn.setText("Back");
  backBtn.setTextBold();
  backBtn.addEventHandler(this, "backClick");
  stopBtn = new GButton(this, 80, 170, 80, 30);
  stopBtn.setText("Stop");
  stopBtn.setTextBold();
  stopBtn.addEventHandler(this, "stopClick");
}

// Variable declarations 
// autogenerated do not edit
GTextArea textarea1; 
GButton sendBtn; 
GTextField textfield1; 
GButton leftBtn; 
GButton rightBtn; 
GButton forwardBtn; 
GButton backBtn; 
GButton stopBtn; 